name: Run php

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        tools: composer, php-curl-class
    - name: run php
      env:
        osf_token: ${{ secrets.OSF_TOKEN }}
        dummy: ${{ secrets.DUMMY}}
      run: |
        echo $dummy
        php test.php -p$dummy
        # php engrxiv_prints.php -posf_token
